<?php

class ParentClass
{
    public function method(string $name)
    {

    }
}

class ChildClass extends ParentClass{
    public function method(int $name)
//  tidak boleh merubah sembarang parameter dari parent class nya
    {
        parent::method($name); // TODO: Change the autogenerated stub
    }
}
